### ISSUE TITLE
Improvement: Enhance `!zu ck` command with channel link

### ISSUE THREAD

**Issue by Weyrd** [MalikAza/pyZUnivers#10]
# Description:

Currently, the !zu ck command does not include a direct link to the channel. To improve user experience, it would be beneficial to incorporate the channel link into the command output. This will allow users to easily access the channel directly from the command response.
# Proposed Changes:

-  Modify the !zu ck command to include the channel link in its output.

- Ensure that the link is formatted correctly and is easily accessible to users.

# Benefits:

- Improved usability and convenience for users.

- Streamlined access to the channel, reducing the need for additional steps.

![image](https://github.com/user-attachments/assets/06e72694-fbbb-4b2e-a8e6-13bc300ae71d)

Channel id: 813980380780691486 (#échange-marché-corpo)

**Comment by MalikAza** [comment]
Previous commit will be used for the bot's code.

**Comment by MalikAza** [comment]
Successfully added to the bot:

```py
embed = discord.Embed(title="ZUnivers - Corpokonar checker",color=discord.Colour(value=0x19BC14),
description=f"<#{ZU.utils.ECHANGE_MARCHE_CORPO_CHANNEL_ID}>\n\n" + "".join([f"- {x[0]} : {x[1]}\n" for x in tobe_tagged]))
```

![](https://github.com/user-attachments/assets/8be5d888-b3dd-43c4-ba5f-48b494816256)
