### ISSUE TITLE
Problème journa/bonus

### ISSUE THREAD

**Issue by Weyrd** [MalikAza/pyZUnivers#6]
Je compte pas les jours sans journa pour le bonus, pour éviter les décalages (qu'avait plot par exemple) mais du coup ça foire le journa du bonus même …
ils peuvent pas juste dire dans leur API : bonus = oui|non

**Comment by MalikAza** [comment]
# La problématique était :
[00:xx] : Checker indique un manque de journa (mais le bonus étais lui aussi prévu pour aujourd'hui)
Le bonus n'est pas manquant, car le journa n'avais pas encore été fait aujourd'hui, en cas d'oublie, le bonus aurait été reporté pour le lendemain.

# Proposition de fix/meilleure implémentation du wrapper :
`bonus_when` n'est plus calculé selon la date d'aujourd'hui, mais selon la date du dernier journa effectué. Ce qui donnes une estimation plus juste de quand le prochain bonus doit être fait.

Dans un checker de bonus, vérifier que le bonus n'est pas à `False` **OU** que la date prévue n'est pas aujourd'hui.
