### ISSUE TITLE
Ajout du canal au pied de page de l'incorporation pour la navigation directe

### ISSUE THREAD

**Issue by Weyrd** [MalikAza/pyZUnivers#8]
## Description

Actuellement, lorsqu'une incorporation est affichée dans un canal sur Zunivers, il n'y a pas de moyen direct pour les utilisateurs de naviguer vers ce canal à partir de l'incorporation. Cela nécessite souvent de quitter l'incorporation et de rechercher manuellement le canal dans l'interface utilisateur de Zunivers. Pour améliorer l'expérience utilisateur et faciliter la navigation, il serait utile d'ajouter le canal au pied de page de l'incorporation, permettant aux utilisateurs de se TP directement vers le canal depuis l'incorporation.

## Proposition de solution

Ajouter un lien ou un bouton cliquable au pied de page de l'incorporation, dirigé vers le canal correspondant. Cela permettrait aux utilisateurs de passer facilement de l'incorporation à la discussion en direct dans le canal concerné, améliorant ainsi la fluidité de l'expérience utilisateur.

## Avantages

- Rendre la navigation plus intuitive et pratique pour les utilisateurs de Zunivers.
- Améliorer l'expérience utilisateur en permettant une transition fluide entre l'incorporation et le canal correspondant.

## Réference
![image](https://github.com/MalikAza/pyZUnivers/assets/44951922/2fe97e0b-11a8-467f-a026-78d7207f146f)

**Comment by MalikAza** [comment]
# Problématique
- Tout lien ne peut être correctement afficher dans le pied de page d'une incorporation de Discord. (Cela concerne à la fois les liens hypertexte `[text](lien)` ou même les liens vers les canaux des serveurs `<#identifiant>`)
- Je ne pense pas que les boutons d'intégrations Discord puisse aussi réaliser ce travail (hormis dans un cas ou l'application Discord est utilisé sur un navigateur Web et non depuis leur application réaliser pour ordinateur ou téléphone mobile).

# Solution suite à un ajout
Depuis [615312a](https://github.com/MalikAza/pyZUnivers/commit/615312aaef6fed7ef4461af0cbfbc9200e732b9e) ; l'implémentation des différents identifiants de canaux pour le serveur Zerator concernant le ZUnivers, a été ajouté.

Je préconise alors l'ajout du lien vers le canal correct, dans la description de l'incorporation ou bien dans un nouveau champ dédié pour cela. La description me semblant être une meilleure approche, au vu du fait que les titre de champs d'incorporation, eux non plus, ne peuvent pas contenir de lien, seulement la valeur de ces derniers le peut. (Et un champ doit obligatoirement avoir un titre)

<p align="center"><img src="https://i.imgur.com/fnvU4Ug.png" height="200" /></p>
